### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by shortymc** [benkaiser/learn-piano#1]
Hello :)
 Thanks for your work and sharing :)

 Learn-Piano looks very cute but i got no sound,
can you help me ?

 Best regards

**Comment by benkaiser** [comment]
You might need to press the button to enable sound. Chrome doesn't like webpages making sounds until they have some user interaction.

**Comment by shortymc** [comment]
okay, but what button ? i try many but no result, i run on firefox

**Comment by benkaiser** [comment]
Firefox does not support web midi: https://caniuse.com/midi
